name: Opam Continuous Integration

on:
  pull_request:
  push:
    branches: [main]

jobs:
 build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - ocaml-base-compiler.4.14.0
          - ocaml-base-compiler.5.3.0
    steps:
      - uses: actions/checkout@v6

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Restore opam cache
        id: opam-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.opam
            $GITHUB_WORKSPACE/_opam
          key: opam-${{ matrix.os }}-${{ matrix.ocaml-compiler }}-${{ hashFiles('*.opam') }}

      - name: Install opam dependencies (*nix)
        if: matrix.os != 'windows-latest'
        run: opam install --deps-only --with-test .

      - name: Install opam dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: opam install --deps-only .

      - name: Build project
        if: matrix.os != 'windows-latest'
        run: opam exec -- dune build @install

      - name: Run tests
        if: matrix.os != 'windows-latest'
        run: opam exec -- dune test

      - name: Run example program
        run: opam exec -- dune exec -- ./examples/main.exe

      - name: Save opam cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.opam
            $GITHUB_WORKSPACE/_opam
          key: opam-${{ matrix.os }}-${{ matrix.ocaml-compiler }}-${{ hashFiles('*.opam') }}
